#!/usr/bin/env python3
import os

def symlink_in_target(source_dir, target_dir):
    source_files = os.listdir(source_dir)
    target_files = os.listdir(target_dir)
    for source_file in source_files:
        if not source_file in target_files:
            symlink_path = os.path.join(target_dir, source_file)
            os.symlink(os.path.join(source_dir, source_file), symlink_path)


if __name__ == '__main__':
    symlink_in_target('/usr/local/bin', '/.cpu-env/bin')
    symlink_in_target('/usr/local/bin', '/.gpu-env/bin')